"""create tables

Revision ID: af5f1e7a2873
Revises: 
Create Date: 2023-07-22 14:42:39.334300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5f1e7a2873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poke_dex', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nick_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('shiny', sa.Boolean(), nullable=False),
    sa.Column('type_one', sa.String(), nullable=False),
    sa.Column('type_two', sa.String(), nullable=True),
    sa.Column('tera_type', sa.String(), nullable=True),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('nature', sa.String(), nullable=False),
    sa.Column('move_one', sa.String(), nullable=True),
    sa.Column('move_two', sa.String(), nullable=True),
    sa.Column('move_three', sa.String(), nullable=True),
    sa.Column('move_four', sa.String(), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_atk', sa.Integer(), nullable=False),
    sa.Column('base_def', sa.Integer(), nullable=False),
    sa.Column('base_sp_atk', sa.Integer(), nullable=False),
    sa.Column('base_sp_def', sa.Integer(), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('ev_hp', sa.Integer(), nullable=False),
    sa.Column('ev_atk', sa.Integer(), nullable=False),
    sa.Column('ev_def', sa.Integer(), nullable=False),
    sa.Column('ev_sp_atk', sa.Integer(), nullable=False),
    sa.Column('ev_sp_def', sa.Integer(), nullable=False),
    sa.Column('ev_speed', sa.Integer(), nullable=False),
    sa.Column('iv_hp', sa.Integer(), nullable=False),
    sa.Column('iv_atk', sa.Integer(), nullable=False),
    sa.Column('iv_def', sa.Integer(), nullable=False),
    sa.Column('iv_sp_atk', sa.Integer(), nullable=False),
    sa.Column('iv_sp_def', sa.Integer(), nullable=False),
    sa.Column('iv_speed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('team_summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teammembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teammembers')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('teams')
    op.drop_table('pokemons')
    op.drop_table('users')
    # ### end Alembic commands ###
